api_platform:
    title: Asset inventory
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        enabled: false
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        multipart:
            mime_types: ['multipart/form-data']
        # html:
        #     mime_types: ['text/html']
    patch_formats:
        jsonld:
            mime_types: ['application/merge-patch+json']
        json:
            mime_types: ['application/merge-patch+json']

    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_maximum_items_per_page: 100
        pagination_client_enabled: true
        pagination_client_items_per_page: true

        extra_properties:
            standard_put: true

    mapping:
        paths:
        - '%kernel.project_dir%/src/File/Entity'
        - '%kernel.project_dir%/src/Tasks/ApiResource'
        - '%kernel.project_dir%/src/Risks/ApiResource'
        - '%kernel.project_dir%/src/Indicators/ApiResource'
        - '%kernel.project_dir%/src/Assets/ApiResource'
        - '%kernel.project_dir%/src/Assets/Entity'
        - '%kernel.project_dir%/src/Assessments/ApiResource'
        - '%kernel.project_dir%/src/Audits/ApiResource'
        - '%kernel.project_dir%/src/Setting/ApiResource'
        - '%kernel.project_dir%/src/Security/Entity'
        - '%kernel.project_dir%/src/Security/ApiResource'

    oauth:
        # To enable or disable OAuth.
        enabled: false
        # The OAuth client ID.
        clientId: ''
        # The OAuth client secret.
        clientSecret: ''
        # The OAuth type.
        type: 'oauth2'
        # The OAuth flow grant type.
        flow: 'application'
        # The OAuth token URL. Make sure to check the specification tokenUrl is not needed for an implicit flow.
        tokenUrl: ''
        # The OAuth authentication URL.
        authorizationUrl: ''
        # The OAuth scopes.
        scopes: []

    swagger:
        swagger_ui_extra_configuration:
            filter: true
