api_platform:
    title: Asset inventory
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        enabled: false
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        # html:
        #     mime_types: ['text/html']
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_maximum_items_per_page: 100
        pagination_client_enabled: true
        pagination_client_items_per_page: true
