monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                # path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: php://stderr
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr



# monolog:
#     channels:
#         - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

# when@dev:
#     monolog:
#         handlers:
#             main:
#                 type: fingers_crossed
#                 action_level: info
#                 handler: console
#                 # excluded_http_codes: [404, 405]
#                 excluded_http_codes: [{ 200: ['^/ping$'] }]
#                 buffer_size: 0 # How many messages should be saved? Prevent memory leaks
#             stream:
#                 type: stream
#                 path: "%kernel.logs_dir%/%kernel.environment%.log"
#                 level: debug
#                 channels: ["!event"]
#                 formatter: 'monolog.formatter.json'
#                 # excluded_http_codes: [{ 200: ['^/ping$'] }]
#             # uncomment to get logging in your browser
#             # you may have to allow bigger header sizes in your Web server configuration
#             #firephp:
#             #    type: firephp
#             #    level: info
#             #chromephp:
#             #    type: chromephp
#             #    level: info
#             console:
#                 type: console
#                 # bubble: false
#                 process_psr_3_messages: false
#                 channels: ["!event", "!doctrine", "!console"]
#                 # formatter: 'monolog.formatter.json'
#                 # formatter: monolog.formatter.console
#                 # excluded_http_codes: [{ 200: ['^/ping$'] }]

# when@test:
#     monolog:
#         handlers:
#             main:
#                 type: fingers_crossed
#                 action_level: error
#                 handler: nested
#                 # excluded_http_codes: [404, 405]
#                 excluded_http_codes: [{ 200: ['/ping'] }]
#                 channels: ["!event"]
#             nested:
#                 type: stream
#                 path: "%kernel.logs_dir%/%kernel.environment%.log"
#                 level: debug

# when@prod:
#     monolog:
#         handlers:
#             main:
#                 type: fingers_crossed
#                 action_level: error
#                 handler: nested
#                 # excluded_http_codes: [404, 405]
#                 excluded_http_codes: [{ 200: ['/ping'] }]
#                 buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#             # nested:
#             #     type: stream
#             #     path: php://stderr
#             #     level: debug
#             #     formatter: monolog.formatter.json
#             console:
#                 type: console
#                 process_psr_3_messages: false
#                 channels: ["!event", "!doctrine"]
#             # deprecation:
#             #     type: stream
#             #     channels: [deprecation]
#             #     path: php://stderr
