twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        settingsService: '@App\Setting\Service\SettingService'
    paths:
        '%kernel.project_dir%/src/Assessments/Template': 'assessments'
        '%kernel.project_dir%/src/Setting/Template': 'setting'
        '%kernel.project_dir%/src/Security/Template': 'security'
        '%kernel.project_dir%/src/Tasks/Template': 'tasks'
        '%kernel.project_dir%/src/Assets/Template': 'asset'
        '%kernel.project_dir%/src/Risks/Template': 'risk'
        '%kernel.project_dir%/vendor/beerfranz/roger-bundle/src/Template': 'roger'

when@test:
    twig:
        strict_variables: true
