twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        settingsService: '@App\Setting\Service\SettingService'
    paths:
        '%kernel.project_dir%/src/Assessments/Template': 'assessments'
        '%kernel.project_dir%/src/Setting/Template': 'setting'

when@test:
    twig:
        strict_variables: true
