request:
  method: POST
  path: /environment_definitions

data:
  identifier: application
  name: Application
  attributes:
    integration:
      - main
      - test1
    preprod:
      - main
    prod:
      - main
      - client1
      - client2
