controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tasks:
    resource:
        path: ../src/Tasks/Controller
        namespace: App\Tasks\Controller
    type: attribute
    # prefix: /ui/tasks
risks:
    resource:
        path: ../src/Risks/Controller
        namespace: App\Risks\Controller
    type: attribute

indicators:
    resource:
        path: ../src/Indicators/Controller
        namespace: App\Indicators\Controller
    type: attribute

assessments:
    resource:
        path: ../src/Assessments/Controller
        namespace: App\Assessments\Controller
    prefix: /ui/assessments
    type: attribute

assets:
    resource:
        path: ../src/Assets/Controller
        namespace: App\Assets\Controller
    type: attribute

setting:
    resource:
        path: ../src/Setting/Controller
        namespace: App\Setting\Controller
    type: attribute

security:
    resource:
        path: ../src/Security/Controller
        namespace: App\Security\Controller
    prefix: /ui/security
    type: attribute

securityPublic:
    resource:
        path: ../src/Security/ControllerPublic
        namespace: App\Security\ControllerPublic
    prefix: /.well-known
    type: attribute

file:
    resource:
        path: ../src/File/Controller
        namespace: App\File\Controller
    type: attribute


# audits:
#     resource:
#         path: ../src/Audits/Controller
#         namespace: App\Audits\Controller
#     type: attribute
