controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tasks:
    resource:
        path: ../src/Tasks/Controller
        namespace: App\Tasks\Controller
    type: attribute
    # prefix: /ui/tasks
risks:
    resource:
        path: ../src/Risks/Controller
        namespace: App\Risks\Controller
    type: attribute
